[[across-web]]
= III. Across Web

artifact

=== AcrossWebModule and ConversionService
AcrossWebModule requires a `FormattingConversionService` bean named *mvcConversionService* to be present.
If there is none, one will be created and exposed.  By default the parent *conversionService* bean will be reused if
it implements the right interface.  If you want to manage the *mvcConversionService* separately, simply create
 a `FormattingConversionService` with the right name in the parent context.

[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Configuration
public class ManualConversionServiceConfiguration
{
	@Bean(name = AcrossWebModule.CONVERSION_SERVICE_BEAN)
	public FormattingConversionService mvcConversionService() {
	    return new FormattingConversionService();
	}
}
----

The *mvcConversionService* will be passed to all `WebMvcConfigurer` instances in order to add formatters.  It is also
the default `ConversionService` attached to the `WebDataBinder`.

NOTE: There will be at least 2 `ConversionService` beans in the across context when `AcrossWebModule` is enabled:
*conversionService* and *mvcConversionService*.  If you have duplicate bean exceptions due to unqualified autowiring,
you should make one of both primary.


=== JSP and Thymeleaf integration
If both JSP and Thymeleaf support are enabled, you can easily use both view types at the same time.  The `AcrossWebModule`
 also provides a tag that can be used to import Thymeleaf templates or fragments in a JSP rendering pipeline.  The same
 model (request attributes) should be available in the Thymeleaf template as in the calling JSP.

[source,html,indent=0]
[subs="verbatim,quotes,attributes"]
----
<%@ taglib prefix="across" uri="http://across.foreach.com/tags" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>JSP including a Thymeleaf template</title>
</head>
<body>
	<across:thymeleaf template="th/mymodule/thymeleaf-from-jsp-include" />
	<div class="child">
		<across:thymeleaf template="th/mymodule/thymeleaf-from-jsp-include :: fragment" />
	</div>
</body>
</html>
----

---

link builders:
prefixing path context
special characters:
- ! = suppress prefix
- {adminWeb}/boe/test/

Extending modules should just define a WebMvcConfigurer component or configuration (does not need to be exposed).
To avoid the default configuration: extend AcrossWebModule and override default context configurers.
If you want to add a custom validator/message codes resolver: add it as bean to the AcrossWebModule before bootstrap.
Working with templates
Building menus
Multipart resolving
