== Bootstrap interaction

[[moduleconfiguration]]
=== @ModuleConfiguration
Any module can provide a number of classes annotated with `@ModuleConfiguration`.
These classes are just like classes annotated with `@Configuration`, except they will not be added to the `ApplicationContext` of the current module, but to the ones of the modules specified in the annotation attributes.

`@ModuleConfiguration` serves as a replacement for `@Configuration`.
All other bean related annotations like conditionals should also work on `@ModuleConfiguration` classes.
Keep in mind however that the actual creation of the beans (and evaluation of conditionals) will happen in the `ApplicationContext` to which the configuration is added, and not necessarily the one of the module defining the class.

.Example of using @ModuleConfiguration
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@ModuleConfiguration(SpringSecurityModule.NAME)
public class SecurityConfiguration
{
	@Autowired
	public void configureGlobal( AuthenticationManagerBuilder auth ) throws Exception {
		auth.inMemoryAuthentication()
		    .withUser( "admin" ).password( "admin" )
		    .authorities( new NamedGrantedAuthority( "access administration" ) );
	}
}
----

WARNING: When not specifying any module on a `@ModuleConfiguration`, the configuration will be added to all modules, including the module defining the class.

.Scanning for `@ModuleConfiguration` classes
By default the sub-packages *config* and *extensions* of an `AcrossModule` will be scanned to detect classes annotated with `@ModuleConfiguration`.
A module can configure these packages by overriding the `getModuleConfigurationScanPackages()` method.

=== Subscribe to events
A module can interact with the configuration of other modules by subscribing to one of the <<bootstrap-events,bootstrap events>>.
This can only be done *during* bootstrap.

=== Customizing your module descriptor
A third approach for customizing module configuration is implementing `prepareForBootstrap()` on you `AcrossModule` module descriptor.
This method is called before the actual bootstrapping of modules happens, which is the last point in time when the configuration of all modules can be modified.

.Example of a prepareForBootstrap
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
    @Override
    public void prepareForBootstrap( ModuleBootstrapConfig currentModule, AcrossBootstrapConfig contextConfig ) {
        if ( ArrayUtils.contains( supportedViews, AcrossWebViewSupport.JSP ) ) {
            currentModule.addApplicationContextConfigurer(
                    new AnnotatedClassConfigurer( JstlViewSupportConfiguration.class ) );
        }
        if ( ArrayUtils.contains( supportedViews, AcrossWebViewSupport.THYMELEAF ) ) {
            currentModule.addApplicationContextConfigurer(
                    new AnnotatedClassConfigurer( ThymeleafViewSupportConfiguration.class ) );
        }
    }
----
