=== Module dependencies

There are several ways to influence the beans that are being bootstrapped with a module, by passing information from the configuration to the actual module ApplicationContext.

==== @AcrossDepends

[discrete]
===== Using @AcrossDepends on a module

Using AcrossDepends annotation on a component class you can avoid beans or Configurations from being created based on the presence of other modules.
required modules: the component will only be created if all required modules are present
optional modules: the component will only be created if at least one of the optional modules is present

[discrete]
===== Using @AcrossDepends on component classes
expression will be evaluated against the module context - as usual - beans from earlier modules will be available

==== TODO: AcrossCondition
AcrossCondition is another implementation of Spring Conditional.
AcrossCondition takes one or more Spring Expression Language (SpEL) statements as value, and all statements must evaluate to true before the component will be created.
It can be used to check environment or module properties (or any property on already existing beans from the parent context).
The current module instance can always be referenced under the key currentModule in the expression.

.Examples using AcrossCondition
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Configuration
@AcrossCondition("#{currentModule.transactionEnabled}")
public class EnableTransactionConfiguration {
    // Only executed if the property isTransactionEnabled() on the AcrossModule instance is true
}

@Controller
@AcrossCondition("${mymodule.testcontroller:true}")
public class MyTestController {
    // The controller would only be created based on the property 'mymodule.testcontroller' in the Environment of the bootstrapping module
    // If the Environment does not contain the property, value 'true' will be used
}
----
