== TODO: Default beans
=== AcrossContextInfo
=== AcrossContextBeanRegistry
=== AcrossInstallerRepository
=== ConversionService
An AcrossContext requires a valid `ConversionService` bean named *conversionService* to be present.
If there is none, a `DefaultFormattingConversionService` will be created and exposed.
If you want to manage the `ConversionService` yourself, simply create a `ConversionService` with the right name in the parent `ApplicationContext`.

The default *conversionService* will also be attached to the `ApplicationContext` environment of every module.
This means property fetching using `Environment.getProperty()` methods will perform type conversion using the `ConversionService` (eg. useful for date property parsing).

.Date conversion
Apart from the `ConversionService` itself, an `AcrossContext` creates a default `StringToDateConverter` bean named *defaultDateConverter*.
This converter supports converting a string to a corresponding date in many common date patterns.
The `StringToDateConverter` assumes a fixed locale that can be configured (default: `US`).

WARNING: If you manage the `ConversionService` outside of the `AcrossContext` the default `StringToDateConverter` will not be registered either.

=== DistributedLockRepository
tbd

=== AcrossDevelopmentMode
Utility bean that can be used to verify if <<development-mode,development mode>> is active, and to get development locations for resources files.