[[development-mode]]
== Development mode
The AcrossContext can have development mode enabled through the *developmentMode* property.
Modules can use development mode to configure different services (or services differently).
An example is auto-reloading and no caching of the message sources if development mode is active.

Apart from setting the *developmentMode* property on `AcrossContext`, development mode can be activated the following way:

. property *across.development.active* is _true_
. Spring profile *dev* is active

.Resource resolving
By default resources (eg. messages, templates) are resolved from the classpath.
It is possible to configure a physical location for the resources of a module if development mode is active (eg on your local filesystem).
This is done in a special properties file that will be looked for in *${user.home}/dev-configs/across-devel.properties*.
The properties file should contain properties where the key references the module name, and the value the physical resources directory.

.Example development properties
[source,text,indent=0]
[subs="verbatim,quotes,attributes"]
----
acrossModule.MyModule.resources=c:/code/mymodule/src/main/resources
acrossModule.OtherModule.resources=c:/code/othermodule/src/main/resources
----