[[across-core]]
=== Across core

sdfjqdshdjsk

[discrete]
==== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>across</groupId>
			<artifactId>across-core</artifactId>
			<version>{across-version}</version>
		</dependency>
	</dependencies>
----

==== Dependencies

== Across version information

Across modules have version information attached in the form of an `AcrossVersionInfo` property.  This object provides
information like the current version and time when it was built.  By default this information is fetched automatically
from the *META-INF/MANIFEST.MF* resource.  The following attributes are required for a fully configured `AcrossVersionInfo`
instance:


.MANIFEST attributes
|===
|Attribute |Example|Description

|*Implementation-Title*
|across-web
|Name of the project the class (`AcrossModule`) belongs to. Often also the JAR name.

|*Implementation-Version*
|{across-version}
|Build version of the `AcrossModule`.

|*Build-Time*
|20150831-1011
|Timestamp when the version was built (in *yyyyMMdd-HHmm* format).

|===

Using Maven a valid MANIFEST file can automatically be created using the following plugin configuration:

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.6</version>
        <configuration>
            <archive>
                <manifest>
                    <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                </manifest>
                <manifestEntries>
                    <Build-Time>${maven.build.timestamp}</Build-Time>
                </manifestEntries>
            </archive>
        </configuration>
    </plugin>
----

== Datasources and installers
An AcrossContext supports the configuration of a DataSource instance.  The datasource will be available for all modules
 as bean named acrossDataSource.  Additionally a second datasource can be configured that will be available as
 the acrossInstallerDataSource.  If no separate installer datasource is specified, the default across datasource
 will be used.

 A valid default datasource is required for installers to run. It is not possible to configure only an installer
 datasource as the distributed locking mechanism uses the default datasource.

 The installer datasource can be wired anywhere, but will be the default datasource used for all
 AcrossLiquibaseInstaller instances.  Its purpose is to provide a separate datasource with augmented permissions
 to perform schema changes and installer tracking in the database.

 For security purposes the installer datasource could be closed after the context has bootstrapped.  This is the
 responsibilty of the application configuration and be aware that some functionality related to querying the
 installer repository will not be available if the installer datasource goes offline.