CREATE USER axt IDENTIFIED BY across_test;
GRANT CONNECT, RESOURCE TO axt;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO axt;
GRANT UNLIMITED TABLESPACE TO axt;
GRANT SELECT ON SYS.DBA_RECYCLEBIN TO AXT;