= Across framework
Arne Vandamme
:toc: left
:sectanchors:
:across-version: 1.1.2-SNAPSHOT
:spring-url: http://projects.spring.io/spring-framework/
:spring-data-url: http://projects.spring.io/spring-data/
:spring-batch-url: http://projects.spring.io/spring-batch/
:spring-security-url: http://projects.spring.io/spring-security/

:numbered!:
[abstract]
== Across in a nutshell
Across is a Java framework that aims to facilitate module based development for Java (web) applications.
It builds heavily on Spring framework and allows defining a module consisting of a number of classes and configuration files.
Every module defines its own Spring application context and can share one or more beans with other modules.

Across modules can contain any set of functionality: low-level add-ons like facilities to activate caching or end user
functionality including web controllers and their views.  Across provides the basic infrastructure to define modules and
make them depend on each other.  A module will most often be a separate jar, but this is in no way a requirement.

The general principle is that every Across module can depend on others, but is responsible for its own installation and
start-up procedures.  To this end, a module can define its own installers.

== What's new in this version?
=== 1.1.2-SNAPSHOT
tbd
EnableAcrossContext extended with attributes - scanning

=== 1.1.1.RELEASE
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
= I. About Across

== Before you begin
To understand what Across is and how it works you should have good knowledge of Java web development as well as
link:{spring-url}[Spring framework and Spring Web MVC].  At the very least you should be familiar with the concepts of dependency
injection (auto-wiring), the `ApplicationContext` and `JavaConfig` configuration style.

== Modular development
Across framework aims to facilitate module based development of your Java applications.  An application would simply
 consist of a collection of modules, where each module brings a set of functionality to the table.  Modules are somewhat
 _knowledgeable_, they _know_ about the application/set-up they are running in and can make decisions based on that
 knowledge.  They know about other modules and the services they provide, and they are able to talk to those other
 modules to provide automatic integration.

Well defined modules can offload work from the developer.  The development team does not need to make the same decisions
 over and over again for every new application.  With a well defined module it needs to be made only once, and in new
 applications the same module will make the same reliable decision.

For modules to be able to do this they have to speak a common language.  In software development terms this means they
 need to implement a same contract (usually in the form of interfaces or base classes).  Providing that common language
 is what Across framework is about.

Across framework gives developers an easy way to create, configure and reuse _smart_ modules.

[discrete]s
=== The difference between libraries and modules
The terms _libraries_ and _modules_ are sometimes used interchangeably in the software development landscape.  The exact
 meaning depends on the context.  When talking about Across we identify the following difference between the two:

A library::
Provides a set of low-level building blocks, infrastructure that can be used to build application logic.  Libraries are
_dumb_, they only do exactly as they have been told by a developer. +
+
In a car analogy libraries could be _wheels_ and _frames_.  Someone - a developer - would still need to decide how to assemble
 the different components to achieve an actual car.
+
In this context http://commons.apache.org/[Apache Commons] is a library, but so is {spring-url}[Spring framework]
as well as the <<across-core>> itself.

A module::
Provides more high-level building blocks in the form of complete functionality requiring little or even no
configuration.  Even with just a few modules present you could get a fully functional application.  Modules are _smart_,
they can make decisions based on their knowledge of the environment they are running in. +
+
In the car analogy a module could in fact be an entire car.  The car knows how to drive, it knows it has four wheels
 and knows the state of every one of them.  Configuration of the module could be the decision of the engine you'd want.


As to deciding whether you want a module or a library, think of it this way: are you required to build a car,
or is your mission to travel from A to B and you simply need a car to be able to do so?

****
In all Across documentation we refer to a *module* as an implementation of an `AcrossModule` that provides
a set of functionality out of the box.
****

[[across-standard-modules]]
=== Across standard modules
Apart from the Across framework itself, a different project maintains a set of Across standard modules.  These modules aim
 to be productivity enhancers by providing you with a common set of functionality that can be used as the foundation
 for your applications or even for an entire web cms.

There are standard modules that provide you with the set-up for an administrative web interface, secured with
 {spring-security-url}[Spring security] and built on top of an entire roles and permissions management domain layer.
 Other modules generate web forms at runtime for persistent entities you have declared in your application.

Across framework provides only a ground layer, the real win is in re-using well-defined modules that have already
been built.  The standard modules projects aims to do exactly that: bring some best of breed modules to the open source Across landscape.

[discrete]
=== Across and Spring framework
{spring-url}[Spring framework] is a de facto industry standard for building Java (web) applications.  It was a logical
 choice to use it as the foundation for Across.  Across extends or even customizes some aspects of Spring, but still supports
 most if not all common Spring functions out of the box.  To use Across optimally, a good knowledge of Spring is required.

<<across-core>> and <<across-web>> build on top of the common Spring framework, while other <<across-standard-modules,standard modules>> integrate different
Spring libraries like {spring-data-url}[Spring Data], {spring-batch-url}[Spring Batch] or {spring-security-url}[Spring security].

[discrete]
=== Across and OSGi
While Across talks about modules just like OSGi does and some similarity between the basic concepts can be found,
 there is currently no relation between the two.  Across modules are not OSGi and the current development does not
 involve developing and testing for OSGi containers.

The focus of Across is more on providing a way to group end-user functionality than it is on a dynamic runtime environment.
Integrating Across applications in the OSGi landscape is on the long-term roadmap.

== Core concepts
At the heart of Across are a couple of concepts you should understand.  The terms related tot these concepts are used
throughout all Across documentation, consider them part of the Across http://en.wikipedia.org/wiki/Domain-specific_language[DSL].

[discrete]
=== context

[discrete]
=== modules

[discrete]
=== dependencies

[discrete]
=== bootstrap

[discrete]
=== installers

[discrete]
=== exposing

[discrete]
=== events

[discrete]
=== refreshing

== Across framework artifacts

[discrete]
=== Overview
Across framework itself consists of 3 artifacts: `across-core`, `across-web` and `across-test`.

across-core:: Supports the configuration of an Across context and provides all necessary infrastructure to define and execute modules.
across-web:: Provides an `AcrossModule` that supports configuration of a web application using Across with the Spring `DispatcherServlet` as the most common scenario.
across-test:: Supports integration testing of your Across modules, both web and non-web related.  Builds on top of `spring-test`.

[discrete]
=== Common dependencies
Across is directly tied to Spring framework and all artifacts come with a set of curated dependencies.
Applications built on top of Across should either manage the dependencies manually by fixing the versions or let the modules pull in the required dependencies transitively.

.Most common dependency versions that almost all modules rely on
|===
| Java | 1.8
| Java Servlet API _(if applicable)_ | 3.0.1
| Spring framework | {spring-version}
|===

[discrete]
=== Repository
All Across related artifacts - both release and snapshot versions - can be fetched from the Foreach Nexus repository.  This also includes the set of <<across-standard-modules>>.

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<repositories>
        <repository>
            <id>foreach-nexus</id>
            <name>Foreach nexus</name>
            <url>http://repository.foreach.be/nexus/content/groups/public/</url>
        </repository>
    </repositories>
----

include::../across-core/src/doc/index.adoc[]
include::../across-web/src/doc/index.adoc[]
include::../across-test/src/doc/index.adoc[]

