== Across in a nutshell
Across is a Java framework for developing your application using a modular approach.
It is built on top of Spring framework and provides a way to define application modules as well as the infrastructure to run the entire application.

*An Across module*

* bundles technical or business domain functionality,
* explicitly depends on zero or more other modules,
* exposes components like services or repositories for other modules to use,
* uses exposed components from other modules,
* has zero or more installers taking care of things like initial data creation or schema migrations,
* is a single Spring `ApplicationContext`.

*An Across application*

* specifies the modules to use,
* sets up common infrastructure (eg. the event bus),
* ensures modules are ordered according to their dependencies and bootstrapped in that same order,
* runs as a Spring Boot application.

Across applications force you to use the modular approach as much as possible.

Across is free and open source, published under an Apache 2.0 license.

