== What's new in this version?
=== 1.1.4.RELEASE
Bugfix release: fixes issue where bootstrap lock was taken even if no installer needed executing.

The bootstrap lock is now no longer kept during the entire bootstrap phase, but is taken on a per-installer level.

=== 1.1.3.RELEASE
Maintenance release containing several bugfixes.

=== 1.1.2.RELEASE
*Across Core*

Across now requires JDK8 and has improved support for Spring Boot.
The latter is also a required dependency as of 1.1.2.
A lot of improvements have been done to reduce the amount of boilerplate code necessary to create a new `AcrossContext`.

* <<enableacrosscontext>> annotation now supports autoconfiguration of an `AcrossContext`
* <<moduleconfiguration>> annotation provides a no-hassle way to declare annotated classes that need to be added to a specific module
* message sources are now <<auto-detecting-message-sources,auto-detected>> if they follow the conventions
* both `AcrossModule` and `ModuleBootstrapConfig` now have shortcut `expose()` methods that make it easier to expose additional beans
* several changes and improvements were made to installers:
** installers are now created in their own configurable <<installer-applicationcontext,installer `ApplicationContext`>>
** installers are detected automatically through classpath scanning (defaults to *installers* package of a module)
** installers are ordered based on the presence of an `@Order` annotation
** installers now support `@Conditional` annotations for building more complex conditions
** installers should only be specified as class names in `getInstallers()`, the use of instances is deprecated
** `InstallerSettings` has been refactored to use `InstallerMetaData` instead (breaking change)
** installers can implement `InstallerActionResolver` directly to suppress execution at runtime
** `AcrossInstallerRepository` now has methods to rename installers
** `AcrossLiquibaseInstaller` detects the most appropriate `SchemaConfiguration` to use and modifies default schema accordingly
* development mode can be set through the property *across.development.active* and is active by default if a Spring profile called *dev* is active

*Across Web*

* <<across-application,@AcrossApplication>> can be used with `SpringApplication` to bootstrap an Across context with dynamic modules and support for embedded servlet containers
* async configuration can now correctly be set through `WebMvcConfigurer#configureAsyncSupport(AsyncSupportConfigurer)`
* `AcrossWebModuleSettings` has been refactored and `AcrossWebModule` can now be <<across-web-module-settings,configured through properties>>
** properties support Spring configuration metadata with possible IDE support
* by default only Thymeleaf views support is activated (breaking change)
* static resources now configure default <<client-side-caching,client-side caching>> and <<resource-url-versioning,resource url versioning>>
* <<dynamic-servlet-registration,dynamic registration of servlets and filters>> now supports ordering
* <<default-http-encoding,default HTTP encoding>> is now forced to UTF-8

*Across Test*

Several improvements have been done for easier integration testing of modules in a web context.

* <<test-builders,test context builders>> have been added for easy configuration of an `AcrossContext` in test methods
* <<mock-across-servlet-context,MockAcrossServletContext>> can now be used for testing of dynamic `ServletContext` configuration
* addition of a `AcrossMockMvcBuilders` class for creating a `MockMvcBuilder` based on an `AcrossContext`
** both <<test-annotations,annotations>> and <<test-builders,builders>> now provide a singleton `MockMvc` instance that is initialized with the bootstrapped context and all dynamically registered filters

=== 1.1.1.RELEASE
Initial public release available on http://search.maven.org/[Maven central].
