= I. About Across

== Before you begin
To understand what Across is and how it works you should have good knowledge of Java web development as well as
link:{spring-url}[Spring framework and Spring Web MVC].  At the very least you should be familiar with the concepts of dependency
injection (auto-wiring), the `ApplicationContext` and `JavaConfig` configuration style.

== Modular development
Across framework aims to facilitate module based development of your Java applications.  An application would simply
 consist of a collection of modules, where each module brings a set of functionality to the table.  Modules are somewhat
 _knowledgeable_, they _know_ about the application/set-up they are running in and can make decisions based on that
 knowledge.  They know about other modules and the services they provide, and they are able to talk to those other
 modules to provide automatic integration.

Well defined modules can offload work from the developer.  The development team does not need to make the same decisions
 over and over again for every new application.  With a well defined module it needs to be made only once, and in new
 applications the same module will make the same reliable decision.

For modules to be able to do this they have to speak a common language.  In software development terms this means they
 need to implement a same contract (usually in the form of interfaces or base classes).  Providing that common language
 is what Across framework is about.

Across framework gives developers an easy way to create, configure and reuse _smart_ modules.

[discrete]
=== The difference between libraries and modules
The terms _libraries_ and _modules_ are sometimes used interchangeably in the software development landscape.  The exact
 meaning depends on the context.  When talking about Across we identify the following difference between the two:

A library::
Provides a set of low-level building blocks, infrastructure that can be used to build application logic.  Libraries are
_dumb_, they only do exactly as they have been told by a developer. +
+
In a car analogy libraries could be _wheels_ and _frames_.  Someone - a developer - would still need to decide how to assemble
 the different components to achieve an actual car.
+
In this context http://commons.apache.org/[Apache Commons] is a library, but so is {spring-url}[Spring framework]
as well as the <<across-core>> itself.

A module::
Provides more high-level building blocks in the form of complete functionality requiring little or even no
configuration.  Even with just a few modules present you could get a fully functional application.  Modules are _smart_,
they can make decisions based on their knowledge of the environment they are running in. +
+
In the car analogy a module could in fact be an entire car.  The car knows how to drive, it knows it has four wheels
 and knows the state of every one of them.  Configuration of the module could be the decision of the engine you'd want.


As to deciding whether you want a module or a library, think of it this way: are you required to build a car,
or is your mission to travel from A to B and you simply need a car to be able to do so?

****
In all Across documentation we refer to a *module* as an implementation of an `AcrossModule` that provides
a set of functionality out of the box.
****

[[across-standard-modules]]
=== Across standard modules
Apart from the Across framework itself, a different project maintains a set of Across standard modules.  These modules aim
 to be productivity enhancers by providing you with a common set of functionality that can be used as the foundation
 for your applications or even for an entire web cms.

There are standard modules that provide you with the set-up for an administrative web interface, secured with
 {spring-security-url}[Spring security] and built on top of an entire roles and permissions management domain layer.
 Other modules generate web forms at runtime for persistent entities you have declared in your application.

Across framework provides only a ground layer, the real win is in re-using well-defined modules that have already
been built.  The standard modules projects aims to do exactly that: bring some best of breed modules to the open source Across landscape.

[[across-platform]]
=== Across platform
Across platform provides a single BOM pom that has a curated list of dependencies for both Across core and Across Standard Modules.
Using the platform is advised for Across based applications as the platform will ensure different module versions play together nicely.

[discrete]
=== Across and Spring framework
{spring-url}[Spring framework] is a de facto industry standard for building Java (web) applications.  It was a logical
 choice to use it as the foundation for Across.  Across extends or even customizes some aspects of Spring, but still supports
 most if not all common Spring functions out of the box.  To use Across optimally, a good knowledge of Spring is required.

<<across-core>> and <<across-web>> build on top of the common Spring framework, while other <<across-standard-modules,standard modules>> integrate different
Spring libraries like {spring-data-url}[Spring Data], {spring-batch-url}[Spring Batch] or {spring-security-url}[Spring security].

[discrete]
=== Across and OSGi
While Across talks about modules just like OSGi does and some similarity between the basic concepts can be found,
 there is currently no relation between the two.  Across modules are not OSGi and the current development does not
 involve developing and testing for OSGi containers.

The focus of Across is more on providing a way to group end-user functionality than it is on a dynamic runtime environment.
Integrating Across applications in the OSGi landscape is on the long-term roadmap.

include::chap-across-spring-boot.adoc[]

== Core concepts
At the heart of Across are a couple of concepts you should understand.  The terms related tot these concepts are used
throughout all Across documentation, consider them part of the Across http://en.wikipedia.org/wiki/Domain-specific_language[DSL].

[discrete]
=== Across context
An Across context is a configured set of Across modules and usually represents a single application.
A single Across context is represented by the `AcrossContext` class but usually created by using <<yrdy,`@EnableAcrossContext`>> or <<yrer,`@AcrossApplication`>>.

Compared to a single Spring `ApplicationContext`, an `AcrossContext` represents an entire hierarchy of `ApplicationContext` instances.
The `AcrossContext` itself is an `ApplicationContext` that can have optionally have a parent `ApplicationContext`.
However every single module loaded in the Across context also is a separate `ApplicationContext` with the Across context as parent.

[discrete]
=== Across module
An Across module represents a grouped set of beans and services that provide application logic and that often other modules can use.
Every module is uniquely identified by its name and is defined by <<creating a descriptor class>> that extends from the `AcrossModule` class.

The `AcrossModule` implementation defines how the module contents should be loaded in the Across context.
If a module adheres to a set of <<conventions>>, required configuration can be kept at a minimum.
For simple applications, it is even possible to define <<package based dynamic modules>> that require no separate descriptor.

[discrete]
=== Module dependencies
Modules can depend on other modules.
If module B depends on module A, B states explicitly that it wishes to make use of the functionality that A will provide.
The module dependencies will determine the loading order of the modules in the configured Across context.

Modules have two types of dependencies on other modules:

* explicit dependencies usually configured with <<`@AcrossDepends`>>
* implicit dependencies defined by the <<module role>>

[discrete]
=== Bootstrapping
An Across context is configured by dermining which modules should be loaded.
The actual creation of the module beans is only done when the Across context <<bootstraps>>.
Bootstrapping an Across context involves the creation of the backing Spring `ApplicationContext` instances.
Every single module will have an `ApplicationContext` configured according to the `AcrossModule` descriptor.
During bootstrapping, all modules are bootstrapped sequentially and in the order determined through their dependencies.

An `AcrossContext` is only successfully bootstrapped if all modules have bootstrapped successfully.
A general `AcrossContext` and `AcrossModule` lifecycle has a start (bootstrap) and stop (shutdown) phase.
In most applications these are managed transparently through the use of `@EnableAcrossContext` or `@AcrossApplication`.

[discrete]
=== Installers
An Across module can define any number of installer beans.
Installers are special beans that will only exist:

* during the bootstrapping of the Across context
* if all conditions for the installers apply

Installers can be used to setup the necessary infrastructure for the services that a module provides.
Common use cases for installers include:

* installing a database schema
* inserting (test) data
* running migration tasks

Across itself provides the mechanism for defining installers and optimizing (conditional) installer execution.

[discrete]
=== Exposing beans
Module B can only use a service of module A if module A has explicitly exposed that service.
A service is usually provided through one or more beans, so that means that module A must expose those beans to its owning Across context.
If that has been done, beans from module B can simply wire the beans from module A directly.
Exposing is the means through which module collaboration is defined.

[discrete]
=== Events
An Across context creates a central event bus that every module has access to.
Any bean can publish events on the bus, and special listeners can catch and handle the events published.

Using events is a common way for modules to provide extensions points to other modules, without forcing dependencies.

[discrete]
=== Refreshing beans
Sometimes it is not possible to define explicit dependencies between modules.
For example where module B depends on module A but creates a bean that A should use.
Because circular dependencies are not allowed the only solution for this would be to use <<refreshable beans>>.

Specially demarcated beans can be refreshed after the entire Across context has finished bootstrapped.
These beans will have their dependencies updated based on the now fully populated `AcrossContext`.
The valid use cases for refreshable beans are limited, and if unsure explicit dependencies or the use of events is preferred.

== Across framework artifacts

[discrete]
=== Overview
Across framework itself consists of 3 library artifacts (`across-core`, `across-web` and `across-test`) and one bill-of-material pom (`standard-module-bom`).

across-core:: Supports the configuration of an Across context and provides all necessary infrastructure to define and execute modules.
across-web:: Provides an `AcrossModule` that supports configuration of a web application using Across with the Spring `DispatcherServlet` as the most common scenario.
across-test:: Supports integration testing of your Across modules, both web and non-web related.  Builds on top of `spring-test`.
standard-module-bom:: BOM pom for creating an Across Standard Module or any module wishing to adhere to the standard module conventions.

There is also a separate {platform-bom-url}[platform-bom] project that provides a bill-of-material for applications built on Across and the Across Standard Modules.

[discrete]
=== Common dependencies
Across is directly tied to Spring framework and all artifacts come with a set of curated dependencies.
Across itself uses the Spring Platform as a basis for all its dependencies.

[discrete]
=== Repository
All Across related artifacts - both release and snapshot versions - can be fetched from the Foreach Nexus repository.  This also includes the set of <<across-standard-modules>>.

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<repositories>
    <repository>
        <id>foreach-nexus</id>
        <name>Foreach nexus</name>
        <url>http://repository.foreach.be/nexus/repository/public/</url>
    </repository>
</repositories>
----

Release version are also available in Maven Central.